spring:
  rabbitmq:
    host : localhost
    port : 5672
    virtual-host : 1C
    username : admin
    password : admin
    listener:
      acknowledge-mode: MANUAL
      queue : testConsumer
  rest :
    uri : http://localhost:8088/send
